### ISSUE TITLE
Do you accept PR?

### ISSUE THREAD

**Issue by JulienMaille** [githubuser0xFFFF/QtFluentDesign#1]
It's quite a smart idea to try to mimic Fluent UI with stylesheets.
I just discovered your repo and wanted to contribute by adding more QWidgets. Are you actively working on this, will you look at push request?
Thanks!

**Comment by githubuser0xFFFF** [comment]
It is a spare time project - so I work on it, if I have some spare time. I accept pull requests and would be glad if you provide some additional widgets.

The idea is, to use only certain colors in the SVGs and to find a way to replace the colors in the SVGs on the fly to use different highlight colors.

**Comment by JulienMaille** [comment]
Thanks, so from what I understand you would like to react to colors changes _on-the-fly_?

**Comment by githubuser0xFFFF** [comment]
For Fluent Design apps it is possible to provide a custom accent color or to use the system windows accent color. So the plan is, to support this in the long term. Because the design is based on CSS and SVG, I need to implement functionality to change the accent color in CSS and SVG on the fly.

**Comment by JulienMaille** [comment]
Where would you need colored svgs?

**Comment by githubuser0xFFFF** [comment]
For all graphics that cannot get painted with plain CSS such as Toggle Switch or Checkbox checkmark.

**Comment by JulienMaille** [comment]
You might want to take a look at https://github.com/UN-GCPDS/qt-material#alternative-qpushbuttons-and-custom-fonts

**Comment by githubuser0xFFFF** [comment]
Wow, great. That is exactly what I would like to implement. Thank you for the Link.

**Comment by JulienMaille** [comment]
> For all graphics that cannot get painted with plain CSS such as Toggle Switch or Checkbox checkmark.

Checkmarks are always white so it's ok to keep a svg.
For radio buttons, I found a way to draw them with css using the current highlight color
Now for switches I suppose the solution is to paint them in cpp instead of using a svg.

**Comment by githubuser0xFFFF** [comment]
I paint switches with SVG.

**Comment by JulienMaille** [comment]
Looks like Windows 11 changed everything!

**Comment by githubuser0xFFFF** [comment]
Yes, so I think the best is to implement the XAML controls from this demo:

https://www.microsoft.com/de-de/p/app/9msvh128x2zt?ranMID=46131&ranEAID=lkHXJgoakFQ&ranSiteID=lkHXJgoakFQ-BSa31ofAMBEl6aSkvZWCsg&epi=lkHXJgoakFQ-BSa31ofAMBEl6aSkvZWCsg&irgwc=1&OCID=AID2200057_aff_7806_1243925&tduid=%28ir__ya1z1rqxugkfqjrs9qawvtqnvu2xrjixh1luzwid00%29%287806%29%281243925%29%28lkHXJgoakFQ-BSa31ofAMBEl6aSkvZWCsg%29%28%29&irclickid=_ya1z1rqxugkfqjrs9qawvtqnvu2xrjixh1luzwid00&activetab=pivot:overviewtab

**Comment by JulienMaille** [comment]
what do you mean with "reimplement the XAML"?

**Comment by githubuser0xFFFF** [comment]
Implement a CSS style that matches the controls in this demo because these are the new controls for upcoming Windows applications.
