### ISSUE TITLE
How to use it in my application?

### ISSUE THREAD

**Issue by rsp4jack** [githubuser0xFFFF/QtFluentDesign#2]

**Comment by githubuser0xFFFF** [comment]
Look at the demo

**Comment by Creepercdn** [comment]
How about toggle switch?

**Comment by Creepercdn** [comment]
I think it's best to package into a library.

**Comment by tsbertalan** [comment]
How about a python qt5 demo? If I just do

```python
with open(stylesheet, "r") as fh:
    self.setStyleSheet(fh.read())
```
only the geometric parts of the style seem to be applied, not any colors.

![Screenshot 2022-10-30 161956](https://user-images.githubusercontent.com/306137/198899873-16178167-5e4e-4bb4-9ed6-65de86c52c2b.png)
